### ISSUE TITLE
Callback URL not posting expected messages from Airtel

### ISSUE THREAD

**Issue by mauladmin** [iplusacademy/moodle-paygw_airtelafrica#1]
In the Moodle logs, the following is the log from Airtel via the Callback URL "**41.223.87.244 - - [23/May/2023:11:26:45 +0000] "POST /payment/gateway/airtelafrica/callback.php HTTP/1.1" 200 4937 "-" "ReactorNetty/0.9.8.RELEASE**". However, the airtel indicates that the URL should post the exact message from Airtel e.g. You have deposited UGX. 200 to such and such a client. The log doesn't show this information.

**Comment by ewallah** [comment]
Where does Airtel forces Apache and Moodle to show the exact message? Please refer to the document where this is asked?
Moodle and Apache are showing logs based on the configuration. (debugging level - tracing level - ....)

**Comment by mauladmin** [comment]
How do I be able to do a test and it generates logs like those for MTN shared by Griet

**Comment by iplusacademy** [comment]
The readme file should be clear:

1. Configure your airtel_africa account with the correct data.
2. Enable enrol_fee plugin 
3. Enable the enrol_fee in a course with the correct currency
4. Log in as a test user
5. Configure the telephone to be a correct airtel_africa phone
6. try to enrol as this test user in the course with the enrol_fee enabled
7. Select airtel_africa as payment type
8. follow all steps in the popup

While you do this, enable in your browser the [console](https://appuals.com/open-browser-console/). There you will see aditional information about the communication with airtel_africa.

Next login as admin in Moodle and check the logs
Next check the php - apache (access/error/other_vhost) - moodle_cron logs to see what went right or wrong.

**Comment by mauladmin** [comment]
Thank you, Renaat. Let me retry and let you know

**Comment by mauladmin** [comment]
> Thank you, Renaat. Let me retry and let you know

I also understand that the Airtel plugin has gone into another development, therefore, I need to confirm if the changes were already incorporated into the old plugin installed on the test server or not. If not, please also provide some guidance on how to install this plugin such that I reinstall the updated one because the README file only shows how to configure it when it’s already installed but doesn’t give guidance on how to install it.

**Comment by iplusacademy** [comment]
The plugin is in the Moodle plugins directory, as a result no special steps have to be done, except be sure to use the latest version (Site administration - General - notifications OR  Site administration - Plugins - plugins overview). 

Perhaps the main site admin also received an email that some plugins were outdated. (cfr [installing plugins](https://docs.moodle.org/402/en/Installing_plugins))

**Comment by iplusacademy** [comment]
Please answer the question: Where does Airtel force Apache and Moodle to show the exact message?

No software can force other software to show any messages. Nor can software be forced to show certain images, they only give  brand **guidelines**.

**Comment by mauladmin** [comment]
> Please answer the question: Where does Airtel force Apache and Moodle to show the exact message?
> 
> No software can force other software to show any messages. Nor can software be forced to show certain images, they only give brand **guidelines**.

According to my understanding, Airtel requires a message posted from its end to our callback url. So the guidance I have always sought is to guide me on how to view such a message and you directed me to Apache access logs. All I need is guidance for me to proceed.

**Comment by iplusacademy** [comment]
Considered as fixed after a succesfull payment without an error.
